// flow-typed signature: f4a17fb93954bcf702a5f92a674d386e
// flow-typed version: <<STUB>>/react-responsive-grid_v0.3.4/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-responsive-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-responsive-grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-responsive-grid/dist/components/Breakpoint' {
  declare module.exports: any;
}

declare module 'react-responsive-grid/dist/components/Container' {
  declare module.exports: any;
}

declare module 'react-responsive-grid/dist/components/Grid' {
  declare module.exports: any;
}

declare module 'react-responsive-grid/dist/components/Span' {
  declare module.exports: any;
}

declare module 'react-responsive-grid/dist/index' {
  declare module.exports: any;
}

declare module 'react-responsive-grid/dist/utils/SpanCalculate' {
  declare module.exports: any;
}

declare module 'react-responsive-grid/webpack.config' {
  declare module.exports: any;
}

declare module 'react-responsive-grid/webpack.config.production' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-responsive-grid/dist/components/Breakpoint.js' {
  declare module.exports: $Exports<'react-responsive-grid/dist/components/Breakpoint'>;
}
declare module 'react-responsive-grid/dist/components/Container.js' {
  declare module.exports: $Exports<'react-responsive-grid/dist/components/Container'>;
}
declare module 'react-responsive-grid/dist/components/Grid.js' {
  declare module.exports: $Exports<'react-responsive-grid/dist/components/Grid'>;
}
declare module 'react-responsive-grid/dist/components/Span.js' {
  declare module.exports: $Exports<'react-responsive-grid/dist/components/Span'>;
}
declare module 'react-responsive-grid/dist/index.js' {
  declare module.exports: $Exports<'react-responsive-grid/dist/index'>;
}
declare module 'react-responsive-grid/dist/utils/SpanCalculate.js' {
  declare module.exports: $Exports<'react-responsive-grid/dist/utils/SpanCalculate'>;
}
declare module 'react-responsive-grid/webpack.config.js' {
  declare module.exports: $Exports<'react-responsive-grid/webpack.config'>;
}
declare module 'react-responsive-grid/webpack.config.production.js' {
  declare module.exports: $Exports<'react-responsive-grid/webpack.config.production'>;
}
