// flow-typed signature: 02021684013e0ad12300b8b446380f7b
// flow-typed version: <<STUB>>/webpack-middleware_v1.5.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-middleware/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-middleware/middleware.js' {
  declare module.exports: $Exports<'webpack-middleware/middleware'>;
}
